[package]
name = "sigproc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

audio = "0.2.0-alpha.3"
rustfft = "6.0.1"
debug_plotter = "0.2.1"
rubato = "0.10.0"
wav = "1.0.0"